# Generated by Django 4.2 on 2023-08-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_institute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
    ]
